--
-- PostgreSQL database dump
--

-- Dumped from database version 15.2
-- Dumped by pg_dump version 15.2

-- Started on 2023-03-30 20:20:54 KST

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 215 (class 1259 OID 16407)
-- Name: User; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."User" (
    id integer NOT NULL,
    intraid character varying(50) NOT NULL,
    avatar character varying(50),
    rating integer NOT NULL,
    wincount integer DEFAULT 0 NOT NULL,
    losecount integer DEFAULT 0 NOT NULL,
    email character varying(50) NOT NULL,
    isotp boolean DEFAULT false NOT NULL
);


ALTER TABLE public."User" OWNER TO postgres;

--
-- TOC entry 3640 (class 0 OID 0)
-- Dependencies: 215
-- Name: TABLE "User"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE public."User" IS '유저';


--
-- TOC entry 3641 (class 0 OID 0)
-- Dependencies: 215
-- Name: COLUMN "User".id; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public."User".id IS '유저 id';


--
-- TOC entry 3642 (class 0 OID 0)
-- Dependencies: 215
-- Name: COLUMN "User".intraid; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public."User".intraid IS '인트라 id';


--
-- TOC entry 3643 (class 0 OID 0)
-- Dependencies: 215
-- Name: COLUMN "User".avatar; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public."User".avatar IS '아바타 이미지 url';


--
-- TOC entry 3644 (class 0 OID 0)
-- Dependencies: 215
-- Name: COLUMN "User".rating; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public."User".rating IS '랭킹 점수';


--
-- TOC entry 3645 (class 0 OID 0)
-- Dependencies: 215
-- Name: COLUMN "User".wincount; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public."User".wincount IS '승';


--
-- TOC entry 3646 (class 0 OID 0)
-- Dependencies: 215
-- Name: COLUMN "User".losecount; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public."User".losecount IS '패';


--
-- TOC entry 3647 (class 0 OID 0)
-- Dependencies: 215
-- Name: COLUMN "User".email; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public."User".email IS '이메일';


--
-- TOC entry 3648 (class 0 OID 0)
-- Dependencies: 215
-- Name: COLUMN "User".isotp; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public."User".isotp IS 'authentic?';


--
-- TOC entry 214 (class 1259 OID 16406)
-- Name: User_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."User" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."User_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 217 (class 1259 OID 16416)
-- Name: channel; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.channel (
    id integer NOT NULL,
    kind integer,
    owner integer,
    roomname character varying(50),
    roompassword character varying(50)
);


ALTER TABLE public.channel OWNER TO postgres;

--
-- TOC entry 3649 (class 0 OID 0)
-- Dependencies: 217
-- Name: COLUMN channel.id; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.channel.id IS '채널 아이디';


--
-- TOC entry 3650 (class 0 OID 0)
-- Dependencies: 217
-- Name: COLUMN channel.kind; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.channel.kind IS '종류';


--
-- TOC entry 3651 (class 0 OID 0)
-- Dependencies: 217
-- Name: COLUMN channel.owner; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.channel.owner IS '방장';


--
-- TOC entry 3652 (class 0 OID 0)
-- Dependencies: 217
-- Name: COLUMN channel.roomname; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.channel.roomname IS '방 제목';


--
-- TOC entry 3653 (class 0 OID 0)
-- Dependencies: 217
-- Name: COLUMN channel.roompassword; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.channel.roompassword IS '방 비밀번호';


--
-- TOC entry 216 (class 1259 OID 16415)
-- Name: channel_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.channel ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.channel_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 16442)
-- Name: channelblacklist; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.channelblacklist (
    "channelId" integer NOT NULL,
    userid integer NOT NULL
);


ALTER TABLE public.channelblacklist OWNER TO postgres;

--
-- TOC entry 3654 (class 0 OID 0)
-- Dependencies: 220
-- Name: COLUMN channelblacklist."channelId"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.channelblacklist."channelId" IS '채널 아이디';


--
-- TOC entry 3655 (class 0 OID 0)
-- Dependencies: 220
-- Name: COLUMN channelblacklist.userid; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.channelblacklist.userid IS '유저 아이디';


--
-- TOC entry 221 (class 1259 OID 16457)
-- Name: channelinfo; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.channelinfo (
    chid integer NOT NULL,
    userid integer NOT NULL,
    isowner boolean NOT NULL,
    isadmin boolean NOT NULL
);


ALTER TABLE public.channelinfo OWNER TO postgres;

--
-- TOC entry 3656 (class 0 OID 0)
-- Dependencies: 221
-- Name: COLUMN channelinfo.chid; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.channelinfo.chid IS '채널 아이디';


--
-- TOC entry 3657 (class 0 OID 0)
-- Dependencies: 221
-- Name: COLUMN channelinfo.userid; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.channelinfo.userid IS '유저 아이디';


--
-- TOC entry 3658 (class 0 OID 0)
-- Dependencies: 221
-- Name: COLUMN channelinfo.isowner; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.channelinfo.isowner IS '방장인가?';


--
-- TOC entry 3659 (class 0 OID 0)
-- Dependencies: 221
-- Name: COLUMN channelinfo.isadmin; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.channelinfo.isadmin IS '관리자인가?';


--
-- TOC entry 222 (class 1259 OID 16472)
-- Name: friendlist; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.friendlist (
    "userId1" integer NOT NULL,
    "userId2" integer NOT NULL
);


ALTER TABLE public.friendlist OWNER TO postgres;

--
-- TOC entry 3660 (class 0 OID 0)
-- Dependencies: 222
-- Name: COLUMN friendlist."userId1"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.friendlist."userId1" IS '유저 아이디1';


--
-- TOC entry 3661 (class 0 OID 0)
-- Dependencies: 222
-- Name: COLUMN friendlist."userId2"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.friendlist."userId2" IS '유저 아이디2';


--
-- TOC entry 219 (class 1259 OID 16427)
-- Name: matchhistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.matchhistory (
    id integer NOT NULL,
    winnerid integer,
    loserid integer,
    status integer,
    mapnumber integer,
    winscore integer,
    losescore integer
);


ALTER TABLE public.matchhistory OWNER TO postgres;

--
-- TOC entry 3662 (class 0 OID 0)
-- Dependencies: 219
-- Name: TABLE matchhistory; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE public.matchhistory IS '매칭 전적';


--
-- TOC entry 3663 (class 0 OID 0)
-- Dependencies: 219
-- Name: COLUMN matchhistory.winnerid; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.matchhistory.winnerid IS '승자';


--
-- TOC entry 3664 (class 0 OID 0)
-- Dependencies: 219
-- Name: COLUMN matchhistory.loserid; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.matchhistory.loserid IS '패자';


--
-- TOC entry 3665 (class 0 OID 0)
-- Dependencies: 219
-- Name: COLUMN matchhistory.status; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.matchhistory.status IS '상태';


--
-- TOC entry 3666 (class 0 OID 0)
-- Dependencies: 219
-- Name: COLUMN matchhistory.mapnumber; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.matchhistory.mapnumber IS '맵';


--
-- TOC entry 3667 (class 0 OID 0)
-- Dependencies: 219
-- Name: COLUMN matchhistory.winscore; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.matchhistory.winscore IS '승리 스코어';


--
-- TOC entry 3668 (class 0 OID 0)
-- Dependencies: 219
-- Name: COLUMN matchhistory.losescore; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.matchhistory.losescore IS '패배 스코어';


--
-- TOC entry 218 (class 1259 OID 16426)
-- Name: matchhistory_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.matchhistory ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.matchhistory_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 16490)
-- Name: userblacklist; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.userblacklist (
    "userId1" integer NOT NULL,
    "userId2" integer NOT NULL
);


ALTER TABLE public.userblacklist OWNER TO postgres;

--
-- TOC entry 3669 (class 0 OID 0)
-- Dependencies: 223
-- Name: COLUMN userblacklist."userId1"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.userblacklist."userId1" IS '유저 아이디1';


--
-- TOC entry 3670 (class 0 OID 0)
-- Dependencies: 223
-- Name: COLUMN userblacklist."userId2"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.userblacklist."userId2" IS '유저 아이디2';


--
-- TOC entry 3469 (class 2606 OID 16414)
-- Name: User User_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."User"
    ADD CONSTRAINT "User_pkey" PRIMARY KEY (id);


--
-- TOC entry 3471 (class 2606 OID 16420)
-- Name: channel channel_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.channel
    ADD CONSTRAINT channel_pkey PRIMARY KEY (id);


--
-- TOC entry 3475 (class 2606 OID 16446)
-- Name: channelblacklist channelblacklist_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.channelblacklist
    ADD CONSTRAINT channelblacklist_pkey PRIMARY KEY ("channelId", userid);


--
-- TOC entry 3477 (class 2606 OID 16461)
-- Name: channelinfo channelinfo_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.channelinfo
    ADD CONSTRAINT channelinfo_pkey PRIMARY KEY (chid, userid);


--
-- TOC entry 3473 (class 2606 OID 16431)
-- Name: matchhistory matchhistory_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.matchhistory
    ADD CONSTRAINT matchhistory_pkey PRIMARY KEY (id);


--
-- TOC entry 3479 (class 2606 OID 16476)
-- Name: friendlist user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.friendlist
    ADD CONSTRAINT user_pkey PRIMARY KEY ("userId1", "userId2");


--
-- TOC entry 3481 (class 2606 OID 16494)
-- Name: userblacklist userblacklist_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.userblacklist
    ADD CONSTRAINT userblacklist_pkey PRIMARY KEY ("userId1", "userId2");


--
-- TOC entry 3482 (class 2606 OID 16421)
-- Name: channel fk_channel_owner_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.channel
    ADD CONSTRAINT fk_channel_owner_user_id FOREIGN KEY (owner) REFERENCES public."User"(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 3485 (class 2606 OID 16447)
-- Name: channelblacklist fk_channelblacklist_id_channel_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.channelblacklist
    ADD CONSTRAINT fk_channelblacklist_id_channel_id FOREIGN KEY ("channelId") REFERENCES public.channel(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 3486 (class 2606 OID 16452)
-- Name: channelblacklist fk_channelblacklist_userid_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.channelblacklist
    ADD CONSTRAINT fk_channelblacklist_userid_user_id FOREIGN KEY (userid) REFERENCES public."User"(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 3487 (class 2606 OID 16462)
-- Name: channelinfo fk_channelinfo_chid_channel_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.channelinfo
    ADD CONSTRAINT fk_channelinfo_chid_channel_id FOREIGN KEY (chid) REFERENCES public.channel(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 3488 (class 2606 OID 16467)
-- Name: channelinfo fk_channelinfo_userid_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.channelinfo
    ADD CONSTRAINT fk_channelinfo_userid_user_id FOREIGN KEY (userid) REFERENCES public."User"(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 3483 (class 2606 OID 16437)
-- Name: matchhistory fk_matchhistory_loserid_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.matchhistory
    ADD CONSTRAINT fk_matchhistory_loserid_user_id FOREIGN KEY (loserid) REFERENCES public."User"(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 3484 (class 2606 OID 16432)
-- Name: matchhistory fk_matchhistory_winnerid_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.matchhistory
    ADD CONSTRAINT fk_matchhistory_winnerid_user_id FOREIGN KEY (winnerid) REFERENCES public."User"(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 3489 (class 2606 OID 16477)
-- Name: friendlist fk_userid1_userid1_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.friendlist
    ADD CONSTRAINT fk_userid1_userid1_user_id FOREIGN KEY ("userId1") REFERENCES public."User"(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 3491 (class 2606 OID 16495)
-- Name: userblacklist fk_userid1_userid1_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.userblacklist
    ADD CONSTRAINT fk_userid1_userid1_user_id FOREIGN KEY ("userId1") REFERENCES public."User"(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 3490 (class 2606 OID 16482)
-- Name: friendlist fk_userid1_userid2_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.friendlist
    ADD CONSTRAINT fk_userid1_userid2_user_id FOREIGN KEY ("userId2") REFERENCES public."User"(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


--
-- TOC entry 3492 (class 2606 OID 16500)
-- Name: userblacklist fk_userid1_userid2_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.userblacklist
    ADD CONSTRAINT fk_userid1_userid2_user_id FOREIGN KEY ("userId2") REFERENCES public."User"(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


-- Completed on 2023-03-30 20:20:54 KST

--
-- PostgreSQL database dump complete
--

